"""initial incident core

Revision ID: ab7fe6f3a550
Revises:
Create Date: 2026-07-12 10:20:20.799430
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ab7fe6f3a550"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "PUBLIC_SOURCE",
                "OPERATOR",
                "SERVICE",
                "SYSTEM",
                name="actor_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("before_snapshot", sa.JSON(), nullable=True),
        sa.Column("after_snapshot", sa.JSON(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_event_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_event_id"), ["event_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_audit_event_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_event_target_id"), ["target_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_trace_id"), ["trace_id"], unique=False)

    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            "CREATE TRIGGER audit_event_no_update BEFORE UPDATE ON audit_event "
            "BEGIN SELECT RAISE(ABORT, 'audit_event is append-only'); END"
        )
        op.execute(
            "CREATE TRIGGER audit_event_no_delete BEFORE DELETE ON audit_event "
            "BEGIN SELECT RAISE(ABORT, 'audit_event is append-only'); END"
        )

    op.create_table(
        "fire_id_counter",
        sa.Column("territory_code", sa.String(length=3), nullable=False),
        sa.Column("next_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint("next_sequence >= 1", name="ck_fire_id_counter_positive"),
        sa.PrimaryKeyConstraint("territory_code"),
    )
    op.create_table(
        "idempotency_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint", "idempotency_key", name="uq_idempotency_endpoint_key"),
    )
    with op.batch_alter_table("idempotency_record", schema=None) as batch_op:
        batch_op.create_index("ix_idempotency_expires", ["expires_at"], unique=False)

    op.create_table(
        "incident_series",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fire_id", sa.String(length=32), nullable=False),
        sa.Column("territory_code", sa.String(length=3), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=True),
        sa.Column("reference_lon", sa.Float(), nullable=False),
        sa.Column("reference_lat", sa.Float(), nullable=False),
        sa.Column("horizontal_uncertainty_m", sa.Float(), nullable=False),
        sa.Column("bbox_min_lon", sa.Float(), nullable=False),
        sa.Column("bbox_max_lon", sa.Float(), nullable=False),
        sa.Column("bbox_min_lat", sa.Float(), nullable=False),
        sa.Column("bbox_max_lat", sa.Float(), nullable=False),
        sa.Column(
            "public_visibility",
            sa.Enum(
                "PUBLIC",
                "LIMITED",
                "SUSPENDED",
                "TOMBSTONED",
                name="public_visibility",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("public_note", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("horizontal_uncertainty_m > 0", name="ck_incident_uncertainty"),
        sa.CheckConstraint("reference_lat >= -90 AND reference_lat <= 90", name="ck_incident_lat"),
        sa.CheckConstraint(
            "reference_lon >= -180 AND reference_lon <= 180", name="ck_incident_lon"
        ),
        sa.CheckConstraint("version >= 1", name="ck_incident_version"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("territory_code", "sequence", name="uq_incident_territory_sequence"),
    )
    with op.batch_alter_table("incident_series", schema=None) as batch_op:
        batch_op.create_index(
            "ix_incident_bbox",
            ["bbox_min_lon", "bbox_max_lon", "bbox_min_lat", "bbox_max_lat"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_incident_series_fire_id"), ["fire_id"], unique=True)

    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            "CREATE VIRTUAL TABLE incident_series_rtree USING rtree("
            "id, min_lon, max_lon, min_lat, max_lat)"
        )
        op.execute(
            "CREATE TRIGGER incident_series_rtree_insert AFTER INSERT ON incident_series BEGIN "
            "INSERT INTO incident_series_rtree VALUES "
            "(new.id, new.bbox_min_lon, new.bbox_max_lon, new.bbox_min_lat, new.bbox_max_lat); END"
        )
        op.execute(
            "CREATE TRIGGER incident_series_rtree_update AFTER UPDATE OF "
            "bbox_min_lon, bbox_max_lon, bbox_min_lat, bbox_max_lat ON incident_series BEGIN "
            "UPDATE incident_series_rtree SET min_lon = new.bbox_min_lon, "
            "max_lon = new.bbox_max_lon, min_lat = new.bbox_min_lat, "
            "max_lat = new.bbox_max_lat WHERE id = new.id; END"
        )
        op.execute(
            "CREATE TRIGGER incident_series_rtree_delete AFTER DELETE ON incident_series BEGIN "
            "DELETE FROM incident_series_rtree WHERE id = old.id; END"
        )

    op.create_table(
        "outbox_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint("attempts >= 0", name="ck_outbox_attempts"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outbox_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_outbox_event_aggregate_id"), ["aggregate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_outbox_event_event_id"), ["event_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_outbox_event_topic"), ["topic"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_event_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "TEXT",
                "IMAGE",
                "VIDEO",
                "SENSOR",
                "OPERATOR",
                "INSTITUTIONAL",
                name="source_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "trust",
            sa.Enum(
                "UNVERIFIED",
                "PARTNER",
                "INSTITUTIONAL",
                "OPERATOR",
                name="source_trust",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("credential_hash", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_source_key"), ["source_key"], unique=True)

    op.create_table(
        "episode",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.String(length=16), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE",
                "UNDER_REVIEW",
                "ACTIVE_CONFIRMED",
                "MONITORING",
                "EXTINGUISHED",
                "CLOSED",
                "SUSPENDED",
                "REJECTED",
                name="incident_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("review_required", sa.Boolean(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("confidence_policy", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ordinal >= 1", name="ck_episode_ordinal"),
        sa.CheckConstraint("version >= 1", name="ck_episode_version"),
        sa.ForeignKeyConstraint(["incident_id"], ["incident_series.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("incident_id", "episode_id", name="uq_episode_public_id"),
        sa.UniqueConstraint("incident_id", "ordinal", name="uq_episode_ordinal"),
    )
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_episode_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(
            "uq_episode_one_current",
            ["incident_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current"),
        )

    op.create_table(
        "model_asset",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "lod", sa.Enum("MOBILE", "DESKTOP", name="asset_lod", native_enum=False), nullable=False
        ),
        sa.Column(
            "state",
            sa.Enum(
                "GENERATED",
                "VALIDATED",
                "PUBLISHED",
                "SUPERSEDED",
                "QUARANTINED",
                "DELETED_TOMBSTONE",
                name="asset_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("glb_url", sa.String(length=2048), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("origin_lon", sa.Float(), nullable=False),
        sa.Column("origin_lat", sa.Float(), nullable=False),
        sa.Column("origin_altitude_m", sa.Float(), nullable=False),
        sa.Column("local_frame", sa.String(length=16), nullable=False),
        sa.Column("meters_per_unit", sa.Float(), nullable=False),
        sa.Column("vertical_datum", sa.String(length=128), nullable=False),
        sa.Column("terrain_source_year", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("meters_per_unit > 0", name="ck_asset_scale"),
        sa.CheckConstraint("size_bytes > 0", name="ck_asset_size"),
        sa.CheckConstraint("version >= 1", name="ck_asset_version"),
        sa.ForeignKeyConstraint(["episode_id"], ["episode.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["incident_id"], ["incident_series.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "incident_id", "episode_id", "version", "lod", name="uq_asset_version_lod"
        ),
    )
    with op.batch_alter_table("model_asset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_asset_asset_id"), ["asset_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_model_asset_episode_id"), ["episode_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_model_asset_incident_id"), ["incident_id"], unique=False
        )

    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "TERRAIN_BAKE",
                "ASSET_PUBLICATION",
                name="job_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "VALIDATING",
                "UPLOADING",
                "VERIFYING",
                "PUBLISHING",
                "SUCCEEDED",
                "RETRY_WAIT",
                "QUARANTINED",
                "CANCELLED",
                name="job_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=False),
        sa.Column("output_payload", sa.JSON(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempt >= 0", name="ck_job_attempt_nonnegative"),
        sa.CheckConstraint("max_attempts >= 1", name="ck_job_max_attempts_positive"),
        sa.ForeignKeyConstraint(["episode_id"], ["episode.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["incident_id"], ["incident_series.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "idempotency_key", name="uq_job_kind_idempotency"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_episode_id"), ["episode_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_job_id"), ["job_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_job_lease_until"), ["lease_until"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_next_attempt_at"), ["next_attempt_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_job_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("observation_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("geometry_type", sa.String(length=16), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("altitude_m", sa.Float(), nullable=True),
        sa.Column("vertical_datum", sa.String(length=128), nullable=True),
        sa.Column("horizontal_uncertainty_m", sa.Float(), nullable=False),
        sa.Column("territory_code", sa.String(length=3), nullable=False),
        sa.Column("toponyms", sa.JSON(), nullable=False),
        sa.Column("canonical_name_hint", sa.String(length=255), nullable=True),
        sa.Column("evidence_hash", sa.String(length=80), nullable=False),
        sa.Column("evidence_license", sa.String(length=255), nullable=False),
        sa.Column("external_reference", sa.String(length=512), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "verification_state",
            sa.Enum(
                "UNVERIFIED",
                "PENDING_REVIEW",
                "VERIFIED",
                "REJECTED",
                name="verification_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attached_incident_id", sa.Integer(), nullable=True),
        sa.Column("attached_episode_id", sa.Integer(), nullable=True),
        sa.Column("proposed_incident_id", sa.Integer(), nullable=True),
        sa.Column("proposed_episode_id", sa.Integer(), nullable=True),
        sa.Column(
            "match_decision",
            sa.Enum("CREATE", "ATTACH", "REVIEW", name="match_decision", native_enum=False),
            nullable=False,
        ),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("margin_to_second_candidate", sa.Float(), nullable=True),
        sa.Column("match_factors", sa.JSON(), nullable=False),
        sa.Column("review_reasons", sa.JSON(), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("horizontal_uncertainty_m > 0", name="ck_observation_uncertainty"),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="ck_observation_lat"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180", name="ck_observation_lon"),
        sa.CheckConstraint("version >= 1", name="ck_observation_version"),
        sa.ForeignKeyConstraint(["attached_episode_id"], ["episode.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["attached_incident_id"], ["incident_series.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["proposed_episode_id"], ["episode.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["proposed_incident_id"], ["incident_series.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_observation_attached_episode_id"), ["attached_episode_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_attached_incident_id"),
            ["attached_incident_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_observation_episode_time", ["attached_episode_id", "observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_evidence_hash"), ["evidence_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_observation_id"), ["observation_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_observation_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_proposed_episode_id"), ["proposed_episode_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_proposed_incident_id"),
            ["proposed_incident_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_observation_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_observation_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "manifest_revision",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision >= 1", name="ck_manifest_revision"),
        sa.ForeignKeyConstraint(["asset_id"], ["model_asset.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["episode_id"], ["episode.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["incident_id"], ["incident_series.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("incident_id", "revision", name="uq_manifest_revision"),
    )
    with op.batch_alter_table("manifest_revision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_manifest_revision_incident_id"), ["incident_id"], unique=False
        )
        batch_op.create_index(
            "uq_manifest_one_current",
            ["incident_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS incident_series_rtree_delete")
        op.execute("DROP TRIGGER IF EXISTS incident_series_rtree_update")
        op.execute("DROP TRIGGER IF EXISTS incident_series_rtree_insert")
        op.execute("DROP TABLE IF EXISTS incident_series_rtree")
        op.execute("DROP TRIGGER IF EXISTS audit_event_no_delete")
        op.execute("DROP TRIGGER IF EXISTS audit_event_no_update")

    with op.batch_alter_table("manifest_revision", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_manifest_one_current",
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current"),
        )
        batch_op.drop_index(batch_op.f("ix_manifest_revision_incident_id"))

    op.drop_table("manifest_revision")
    with op.batch_alter_table("observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observation_trace_id"))
        batch_op.drop_index(batch_op.f("ix_observation_source_id"))
        batch_op.drop_index(batch_op.f("ix_observation_proposed_incident_id"))
        batch_op.drop_index(batch_op.f("ix_observation_proposed_episode_id"))
        batch_op.drop_index(batch_op.f("ix_observation_observed_at"))
        batch_op.drop_index(batch_op.f("ix_observation_observation_id"))
        batch_op.drop_index(batch_op.f("ix_observation_evidence_hash"))
        batch_op.drop_index("ix_observation_episode_time")
        batch_op.drop_index(batch_op.f("ix_observation_attached_incident_id"))
        batch_op.drop_index(batch_op.f("ix_observation_attached_episode_id"))

    op.drop_table("observation")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_trace_id"))
        batch_op.drop_index(batch_op.f("ix_job_state"))
        batch_op.drop_index(batch_op.f("ix_job_next_attempt_at"))
        batch_op.drop_index(batch_op.f("ix_job_lease_until"))
        batch_op.drop_index(batch_op.f("ix_job_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_incident_id"))
        batch_op.drop_index(batch_op.f("ix_job_episode_id"))

    op.drop_table("job")
    with op.batch_alter_table("model_asset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_asset_incident_id"))
        batch_op.drop_index(batch_op.f("ix_model_asset_episode_id"))
        batch_op.drop_index(batch_op.f("ix_model_asset_asset_id"))

    op.drop_table("model_asset")
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_episode_one_current",
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current"),
        )
        batch_op.drop_index(batch_op.f("ix_episode_incident_id"))

    op.drop_table("episode")
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_source_key"))

    op.drop_table("source")
    with op.batch_alter_table("outbox_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_event_trace_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_event_topic"))
        batch_op.drop_index(batch_op.f("ix_outbox_event_event_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_event_aggregate_id"))

    op.drop_table("outbox_event")
    with op.batch_alter_table("incident_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_series_fire_id"))
        batch_op.drop_index("ix_incident_bbox")

    op.drop_table("incident_series")
    with op.batch_alter_table("idempotency_record", schema=None) as batch_op:
        batch_op.drop_index("ix_idempotency_expires")

    op.drop_table("idempotency_record")
    op.drop_table("fire_id_counter")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_trace_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_target_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_event_event_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_action"))

    op.drop_table("audit_event")
    # ### end Alembic commands ###
